//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderId { get; set; }
        public int CustId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal Subtotal { get; set; }
        public string Shipping { get; set; }
        public decimal Total { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<int> OrderItem_OrderId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual OrderItems OrderItems { get; set; }
    }
}
