//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesBook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesBook()
        {
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public int SalesBookId { get; set; }
        public byte[] TimeStamp { get; set; }
        public string TitleAction { get; set; }
        public int BookId { get; set; }
    
        public virtual Books Books { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItems> OrderItems { get; set; }
    }
}
